= Neo4j Documentation UI
// Version
:latest-version: v0.4.0
// Settings
:experimental:
// GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Usage

To use this UI with Antora, add the following configuration to your playbook file:

[source,yml,subs=+attributes]
----
ui:
  bundle:
    url: https://static-content.neo4j.com/build/ui-bundle-latest.zip
----


== Installation

[source,sh]
npm i

== Build

To build the UI, run the build command:

[source,sh]
npm run build

== Preview

You can run a local server to preview the UI by running:

[source,sh]
npm start

This will launch a server at http://localhost:5252.

[TIP]
====
You can configure the port using the environment variable `PORT`. For instance, if you want to launch the server on port 3000:

[source,sh]
PORT=3000 npm start
====


== Publish a new UI bundle version

The release process is automated and uses GitHub Actions.
See the `.github/workflows/release.yml` file for details.

The release is performed when a tag is pushed.

. Use `npm version patch` (i.e. 0.1.1 -> 0.1.2) or `npm version minor` (i.e. 0.1.1 -> 0.2.0) to increase the version in the `package.json` file and create a tag for the new version. Running these commands will make the changes AND create a commit.
. Push the tag upstream:
+
 $ git push --tags origin master

The UI bundle is published to S3.
It is available from two URLs:

- `\https://static-content.neo4j.com/build/ui-bundle-vx.y.z.zip`
- `\https://static-content.neo4j.com/build/ui-bundle-latest.zip`

When the tag is pushed, a TC build is triggered, which generates and publishes the latest `.css`, `.js` and other assets.
If the changes to the bundle include updates to any of the templates in _src/layouts_ or _src/partials_, each docset needs to be rebuilt with the new bundle and republished for the changes to take effect.
