= Neo4j Documentation UI
// Version
:latest-version: v0.4.0
// Settings
:experimental:
// GitHub
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Usage

To use this UI with Antora, add the following configuration to your playbook file:

[source,yml,subs=+attributes]
----
ui:
  bundle:
    url: https://s3-eu-west-1.amazonaws.com/static-content.neo4j.com/build/ui-bundle-{latest-version}.zip
----

NOTE: If you want to use the latest version (unreleased) you can use the following URL: `\https://s3-eu-west-1.amazonaws.com/static-content.neo4j.com/build/ui-bundle.zip`.

== Installation

In order to build the UI:

[source,sh]
npm i

== Build

To build the UI, run the build command:

[source,sh]
npm run build

== Preview

You can run a local server to preview the UI by running:

[source,sh]
npm start

This will launch a server at http://localhost:5252.

[TIP]
====
You can configure the port using the environment variable `PORT`. For instance, if you want to launch the server on port 3000:

[source,sh]
PORT=3000 npm start
====


== Publish a new version

The release process is automated and relies on GitHub Actions.
See the `.github/workflows/release.yml` file for details.

The release will be performed when a tag is pushed, the procedure is:

. Tag and push to `master` (don't forget the `v` prefix and replace `x.y.z` with an actual version):
+
 $ git tag vx.y.z && git push origin master --tags

The UI bundle will be published to S3 and available shortly at: `\https://s3-eu-west-1.amazonaws.com/static-content.neo4j.com/build/ui-bundle-vx.y.z.zip`

The UI bundle and docs pages are shipped/built separately. You don't have to rebuild docs projects for them to take the updated UI bundle, but you do need to run the TC build located at `documentation / UI / Publish UI` for the latest tag of the UI bundle to be deployed.
