= Admonitions



== NOTE

[NOTE]
====
You've been down _this_ road before.

`$ npm i -g @antora/cli @antora/site-generator-default`

* list 1
* list 2

Link example: link:https://neo4j.com[Neo4j]

Xref example: xref:alpha.adoc[]
====

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

== TIP

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.

[TIP]
====
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.
====



== IMPORTANT

[IMPORTANT]
====
Don't forget this step!

 $ npm i -g @antora/cli @antora/site-generator-default

* list 1
* list 2

Link example: link:https://neo4j.com[Neo4j]

Xref example: xref:alpha.adoc[]
====



== CAUTION

[CAUTION]
====
[#inline]#I wouldn't try that if I were you.#

 $ npm i -g @antora/cli @antora/site-generator-default

* list 1
* list 2

Link example: link:https://neo4j.com[Neo4j]

Xref example: xref:alpha.adoc[]
====

== WARNING

[WARNING]
====
Watch out!

 $ npm i -g @antora/cli @antora/site-generator-default

* list 1
* list 2

Link example: link:https://neo4j.com[Neo4j]

Xref example: xref:alpha.adoc[]
====



== TIP

.Key Points to Remember
[TIP]
====
If you installed the CLI and the default site generator globally, you can upgrade both of them with the same command.

 $ npm i -g @antora/cli @antora/site-generator-default

* list 1
* list 2

Link example: link:https://neo4j.com[Neo4j]

Xref example: xref:alpha.adoc[]
====

== Admonition block margins

[NOTE]
====
Admonition block with a single paragraph of text.
====

[NOTE]
====
Admonition block with multiple paragraphs.

This is the second paragraph.
====

[NOTE]
====
Admonition block with multiple different elements.

- List item 1
- List item 2

Paragraph of text.
====

[NOTE]
====
Admonition block with multiple different elements.

- List item 1
- List item 2

```
$ npm i -g @antora/cli @antora/site-generator-default
```
====

.Admonition with title text
[NOTE]
====
Admonition block with multiple different elements.

- List item 1
- List item 2

```
$ npm i -g @antora/cli @antora/site-generator-default
```
====

[WARNING]
====
```
$ npm i -g @antora/cli @antora/site-generator-default
```

```
$ npm i -g @antora/cli @antora/site-generator-default
```
====

.Admonition with title text
[WARNING]
====
```
$ npm i -g @antora/cli @antora/site-generator-default
```
====

Nominavi luptatum eos, an vim hinc philosophia intellegebat.
Eu mea inani iriure.