= Cypher Cheat Sheet
:neo4j-docs-base-uri: https://neo4j.com/docs
:page-theme: cheat-sheet
:page-slug: cheat-sheet
// :page-show-labels: true
:page-no-toolbar: true


== How the cheat sheet works

// this has no product, which means it matches all products
=== Example structure

=====
[source, cypher, role=noheader]
-----
[.neo4j-ee] <1>
==== <2>
[source, cypher, role=noheader] <3>
---- 
MATCH (n)
RETURN n AS node
----

[.description] <4>
--  <5>
Description

More description
--
====
-----

[.description]
--
<1> Add a role for each cheat-sheet that the example applies to. Leave blank if it applies in all cases.
<2> Use an example block to contain the Cypher example and description.
<3> Add an optional block for a Cypher example, specifying `[source, cypher,`role=noheader`].
<4> Add a required description block.
<5> If the description consists of more than one paragraph of text, use an open block.
--
=====


=== Playbook configuration

=====
[source, cypher, role=noheader]
-----
asciidoc:
  attributes:
    page-cheatsheets: <1>
      - name: 'Neo4j Enterprise Edition' <2>
        label: 'Enterprise Edition' <3>
        class: 'neo4j-ee' <4>
        default: true <5>
      - name: 'Neo4j Community Edition'
        class: 'neo4j-ce'
      - name: 'Deprecated'
        class: 'deprecated'
        label-only: true <6>
-----

[.description]
--
<1> Add a `page-cheatsheets` section to the playbook to define the different views that a user can choose from. In this example we've added two views: Neo4j Enterprise Edition and Neo4j Community Edition.
<2> Add a name for each view. This text is displayed in the dropdown that you use to select which Cheat Sheet you want to view. 
<3> [Optional] Add label text. When an example is not applicable in all views, a label is displayed to indicate which views it applies to. If no `label` value is specified, the value of `name` is used. 
<4> Specify a class for each view. This is used to add a role to the example block. For example, the class `neo4j-ee` is specified by `[.neo4j-ee]`.
<5> Specify a default view. This is the view that is displayed when the page is loaded.
<6> If you want to display a label for some entries without that label appearing in the dropdown, you can use the `label-only` attribute. In this example, entries that have the `[.deprecated]` role will have the `Deprecated` label displayed, but 'Deprecated' is not an option you can select from the dropdown. In this preview build, both `Configuration` and `Deprecated` have been added as `label-only` views.
--
=====


== Section title


=== Subsection title


====
[source, cypher, role=noheader]
----
<CYPHER EXAMPLE>
----

[.description]
Text describing the example. This example has no role, and therefore no labels. It is displayed in all views.
====

[.neo4j-ee]
====
[source, cypher, role=noheader]
----
<CYPHER EXAMPLE>
----

[.description]
This example only applies to Neo4j Enterprise Edition and is marked with the `[.neo4j-ee]` role.
====


[.read]
== Read queries


=== Read queries subsection


====
[source, cypher, role=noheader]
----
<CYPHER EXAMPLE>
----

[.description]
Text describing the example. This example has no role, and therefore no labels. It is displayed in all views.
====

[.neo4j-ee]
====
[source, cypher, role=noheader]
----
<CYPHER EXAMPLE>
----

[.description]
This example only applies to Neo4j Enterprise Edition and is marked with the `[.neo4j-ee]` role.
====


== Write queries


=== Write queries subsection


====
[source, cypher, role=noheader]
----
<CYPHER EXAMPLE>
----

[.description]
Text describing the example. This example has no role, and therefore no labels. It is displayed in all views.
====


[.neo4j-ee]
====
[source, cypher, role=noheader]
----
<CYPHER EXAMPLE>
----

[.description]
This example only applies to Neo4j Enterprise Edition and is marked with the `[.neo4j-ee]` role.
====


=== link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/match/[Title with link^]


====
[.description]
This entry has no example code.
====


====
[.description]
--
This entry has no example code.

It contains:

- more than one paragraph
- a list

Therefore it is formatted as an open block
--
====


[.neo4j-ee]
====
[source, cypher, role=noheader]
----
MATCH (n)
RETURN n AS node
----

[.description]
Displayed for Neo4j Enterprise Edition

[.extra]
--
Some additional content.
Can be any arbitrary asciidoc blocks and elements.

|===
| Name | Description

| Asciidoctor
| *Awesome* way to write documentation

| Micronaut
| Low resource usage and fast startup micro services
|===
--
====


[.neo4j-ee]
====
[source, cypher, role=noheader]
----
MATCH (n)
RETURN n AS node
----

[.description]
Displayed for Neo4j Enterprise Edition
====


====
[source, cypher, role=noheader]
----
MATCH (n:A&B)
RETURN n.name AS name
----

[.description]
This example is displayed in all views.
====


[.aura-dbe]
====
[source, cypher, role=noheader]
----
MATCH (n:A&B)
RETURN n.name AS name
----

[.description]
This example is displayed for AuraDB Enterprise (`[.aura-dbe]`)
====


[.aura-dbf.aura-dbe]
====
[source, cypher, role=noheader]
----
MATCH (n:A|B)
RETURN n.name AS name

----

[.description]
This example is displayed for both AuraDB Free and AuraDB Enterprise.
====



== Not on Aura


[.neo4j-ce.neo4j-ee]
=== Not on Aura examples

====
[.description]
--
This section applies to Neo4j Community Edition and Neo4j Enterprise Edition. It does not apply to any flavour of Aura.
So, we've added two roles: `[.neo4j-ce.neo4j-ee]`.

When generating a Neo4j (ie not Aura) cheat sheet, we would only add those two versions to the playbook:

[source, asciidoc, role=noheader]
----
- name: 'Neo4j Community Edition'
  class: 'neo4j-ce'
- name: 'Neo4j Enterprise Edition'
  class: 'neo4j-ee'
  default: true
----

In this example the labels would _not_ be displayed.

If we add any other versions to the playbook, such as AuraDB Enterprise, the labels will be displayed when viewing the examples for Neo4j Community Edition or Neo4j Enterprise Edition, but the content will be hidden entirely when viewing the AuraDB Enterprise examples.
--
====

[.neo4j-ce]
== Neo4j Community Edition Only


=== Labeling example


====
[.description]
The title of this section has a `[.neo4j-ce]` role. All subsections and examples within this section will be treated as Neo4j Community Edition only.
Labels are not automatically added to each subsection or example, but they are all hidden when a cheat sheet view other than Neo4j Community Edition is selected.
====


====
[source, cypher, role=noheader]
----
<NEO4J COMMUNITY EDITION CYPHER EXAMPLE>
----

[.description]
This example is not explicitly marked as Neo4j Community Edition, but it is in a section that is marked as Neo4j Community Edition.
It is displayed or hidden accordingly.
====


[.deprecated]
== Deprecated


[.deprecated]
=== Deprecated examples


[.deprecated]
====
[.description]
This section contains deprecated examples. The section has a `[.deprecated]` role, and the subsection and examples also have the role.
That's a lot of labels. 
====


[.deprecated]
====
[source, cypher, role=noheader]
----
(neo4j:Neo4j {name: "Neo4j"})
(neo4j)-[:INCLUDES]->(browser:Product {name: "Neo4j Browser"})
(browser)-[:HAS]->(:Feature {name: "Cypher"})
(browser)-[:HAS]->(:Feature {name: "Dev Tools"})
(browser)-[:HAS]->(:Feature {name: "Visualization"})
(neo4j)-[:CONNECTS_WITH]->(drivers:Drivers {name: "Drivers"})
(drivers)-[:SUPPORTS]->(:Language {name: "Java"})
----

[.description]
Deprecated cypher example.
====


== Functions


=== Temporal functions


====
[source, cypher, role=noheader]
----
date('2018-04-05')
----

[.description]
Returns a date parsed from a string.
====


====
[source, cypher, role=noheader]
----
localtime('12:45:30.25')
----

[.description]
Returns a time with no time zone.
====


====
[source, cypher, role=noheader]
----
time('12:45:30.25+01:00')
----

[.description]
Returns a time in a specified time zone.
====


====
[source, cypher, role=noheader]
----
localdatetime('2018-04-05T12:34:00')
----

[.description]
Returns a datetime with no time zone.
====


====
[source, cypher, role=noheader]
----
datetime('2018-04-05T12:34:00[Europe/Berlin]')
----

[.description]
Returns a datetime in the specified time zone.
====


====
[source, cypher, role=noheader]
----
datetime({epochMillis: 3360000})
----

[.description]
Transforms 3360000 as a UNIX Epoch time into a normal datetime.
====


[.neo4j-ce.aura-dbe]
====
[source, cypher, role=noheader]
----
date({year: $year, month: $month, day: $day})
----

[.description]
All of the temporal functions can also be called with a map of named components.
This example returns a date from year, month and day components.
Each function supports a different set of possible components.
====


====
[source, cypher, role=noheader]
----
datetime({date: $date, time: $time})
----

[.description]
Temporal types can be created by combining other types.
This example creates a datetime from a date and a time.
====


====
[source, cypher, role=noheader]
----
date({date: $datetime, day: 5})
----

[.description]
Temporal types can be created by selecting from more complex types, as well as overriding individual components. This example creates a date by selecting from a datetime, as well as overriding the day component.
====


====
[source, cypher, role=noheader]
----
WITH date('2018-04-05') AS d
RETURN d.year, d.month, d.day, d.week, d.dayOfWeek
----

[.description]
Accessors allow extracting components of temporal types.
====
