= Import your data
:page-layout: docs-ndl
:page-theme: docs
:page-role: explainer
:page-show-home-link: true
:page-hide-nav-title: true
// :page-disablefeedback: true
:page-toclevels: 0


ifndef::backend-pdf[]
++++
<div class="video widget responsive-embed">
<iframe width="680" height="425" src="https://www.youtube.com/embed/2iYTAgXM_ug" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
++++
endif::[]



[.cards.selectable]
== How to use your own data on a graph database

This section is designed to help you learn how to import various types of data into Neo4j. From JSON to APIs to another database, you can retrieve data from nearly any source and use it to populate your graph.


[role=label--new-5.12]
=== `LOAD CSV`
[.icon]
image:icons/ndl/icon-import.svg[]

[.description]
Use Cypher for importing bulk data into Neo4j. Suited for non-admin users.

[.link]
link:{docs-home}/cypher-manual/current/clauses/load-csv/[]


[.labs.label--labs]
=== From relational into graph

[.icon]
image:icons/ndl/icon-csvtodb.svg[]

[.description]
Learn how to translate and migrate tabular data and relational datasets into a graph database.

[.link]
link:{docs-home}/data-import/relational-to-graph-import/[]


[.not-selectable]
=== Neo4j Connectors

[.icon]
image:icons/ndl/icon-connectors.svg[]

[.description]
Learn how to use connectors to connect data from various sources into Neo4j.

[.link]
link:{docs-home}/connectors/[]


[.label--graph-academy.label--featured]
=== Graph Academy

[.icon]
image:icons/ndl/icon-neo4j.svg[]

[.description]
Start using Neo4j's tool for importing data and get started quickly with testing and prototyping.

[.link]
link:{docs-home}/data-importer/current/[]

=== Neo4j Admin Import

[.icon]
image:icons/ndl/icon-admin.svg[]

[.description]
Use Neo4j admin import for initial loading of large amounts of data.

[.link]
link:{docs-home}/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/#import-tool-full[]

=== APOC

[.icon]
image:icons/ndl/icon-library.svg[]

[.description]
Learn how to import data from various data formats, including JSON, XML, and XLS using the APOC library.

[.link]
link:{docs-home}/apoc/current/import/[*Import data using APOC Core*]


[.cards.selectable]
== Keep exploring


[.graph-academy.label--graph-academy.label--featured]
=== GraphAcademy

[.icon]
image:icons/ndl/icon-graphacademy.svg[]

[.description]
Learn how to import CSV data into Neo4j using Cypher.

[.link]
link:https://graphacademy.neo4j.com/courses/importing-cypher/[*GraphAcademy: Importing CSV data into Neo4j*]


=== Import CSV data with Neo4j Desktop

[.icon]
image:icons/ndl/icon-import.svg[]

[.description]
Learn how to use CSV files to import data to a graph with Neo4j Desktop.

[.link]
link:{docs-home}/getting-started/appendix/tutorials/guide-import-desktop-csv/[*How-To: Import CSV data with Neo4j Desktop*]


=== Importing JSON data from a REST API into Neo4j

[.icon]
image:icons/ndl/icon-neo4j.svg[]

[.description]
See techniques for loading data from JSON-based REST APIs into Neo4j.

[.link]
link:{docs-home}/getting-started/data-import/json-rest-api-import/[*Importing JSON data from a REST API into Neo4j*]



[.next-steps]
== Keep exploring

Here are some recommended resources start importing your data:

* link:https://graphacademy.neo4j.com/courses/importing-cypher/[GraphAcademy: Importing CSV data into Neo4j]
+ 
Learn how to import CSV data into Neo4j using Cypher.

* link:{docs-home}/getting-started/appendix/tutorials/guide-import-desktop-csv/[How-To: Import CSV data with Neo4j Desktop]
+ 
Learn how to use CSV files to import data to a graph with Neo4j Destktop.

* link:{docs-home}/getting-started/data-import/json-rest-api-import/[Importing JSON data from a REST API into Neo4j]
+
See techniques for loading data from JSON-based REST APIs into Neo4j.

[.next-steps]
== Keep exploring

Here are some recommended resources start importing your data:

. link:https://graphacademy.neo4j.com/courses/importing-cypher/[GraphAcademy: Importing CSV data into Neo4j]
+ 
Learn how to import CSV data into Neo4j using Cypher.

. link:{docs-home}/getting-started/appendix/tutorials/guide-import-desktop-csv/[How-To: Import CSV data with Neo4j Desktop]
+ 
Learn how to use CSV files to import data to a graph with Neo4j Destktop.

. link:{docs-home}/getting-started/data-import/json-rest-api-import/[Importing JSON data from a REST API into Neo4j]
+
See techniques for loading data from JSON-based REST APIs into Neo4j.
