= Neo4j Tools
:page-theme: docs
:page-role: hub
:page-layout: docs-ndl
:page-show-home-link: true
:page-hide-nav-title: true
// :page-disablefeedback: true
:page-toclevels: -1

[.cards.not-selectable]
== Developer tools documentation

Use Neo4j tools to query and manage your databases, import data, and create graphical visualizations. 

=== Neo4j Bloom/Explore

[.icon]
image:icons/ndl/icon-scientist.svg[]

[.description]
Visualize and explore graph data using natural language search and an intuitive and graphical interface.

[.link]
link:{docs-home}/bloom-user-guide/[Neo4j Bloom] +
link:{docs-home}/aura/preview/explore/introduction/[Explore (Aura)]

=== Neo4j Browser/Query

[.icon]
image:icons/ndl/icon-scientist.svg[]

[.description]
Write and execute Cypher queries and visualize the results in nodes and relationships.

[.link]
link:{docs-home}/browser-manual/[Neo4j Browser] +
link:{docs-home}/aura/preview/query/introduction/[Query (Aura)]

=== Neo4j Browser/Query

[.icon]
image:icons/ndl/icon-scientist.svg[]

[.description]
Write and execute Cypher queries and visualize the results in nodes and relationships.

[.link]
link:{docs-home}/browser-manual/[Neo4j Browser] +
link:{docs-home}/aura/preview/query/introduction/[Query (Aura)]

[.display.card.selectable]

=== Neo4j Data Importer

[.category]
Neo4j Data Importer

[.icon]
image:icons/ndl/icon-scientist.svg[]

[.description]
Learn how to model and import data to your Neo4j database.

[.link]
link:{docs-home}/data-importer[]

[.display.card.selectable]

=== Neo4j Desktop

[.category]
Neo4j Desktop

[.icon]
image:icons/ndl/icon-scientist.svg[]

[.description]
Learn how to experience Neo4j on your local desktop.

[.link]
link:{docs-home}/desktop-manual[]

[.display.card.selectable]

=== Neo4j Ops Manager

[.icon]
image:icons/ndl/icon-scientist.svg[]

[.category]
Neo4j Ops Manager

[.description]
Learn how to monitor, administer, and operate all of the Neo4j DBMSs in an Enterprise with Neo4j Ops Manager.

[.link]
link:{docs-home}/ops-manager[]