= Neo4j documentation
:page-layout: docs-home
:page-theme: docs
:page-hide-nav-title: true
:!toc:
:page-toclevels: -1

[.display]
== Recommended resources

=== Neo4j DBMS

[.icon]
// include::partial$neo4j-icon-svg.adoc[]
image:icon-database.svg[]

[.description]
Learn about graph database concepts, introduce yourself to Cypher, and find useful resources.

[.link]
link:{docs-home}/getting-started[Get started]

=== Neo4j AuraDB

[.icon]
image:icon-cloud-file.svg[]

[.description]
Learn how to create accounts, manage databases, and access AuraDB via cloud providers.

[.link]
link:{docs-home}/aura[Get started]

=== Cypher

[.icon]
image:icon-cypher.svg[]

[.description]
Learn about Cypher, the graph query language for Neo4j and AuraDB.

[.link]
link:{docs-home}/cypher-manual[Get started]

=== Upgrade or migrate

[.icon]
image:icon-upgrade.svg[]

[.description]
Learn how to keep your Neo4j deployment up-to-date.

[.link]
link:{docs-home}/upgrade-migration-guide[Upgrade / Migrate]

=== Connect your application

[.icon]
image:icon-connect.svg[]

[.description]
Discover the drivers, APIs, and connectors that facilitate the use of Neo4j and AuraDB.

[.link]
xref:drivers-apis.adoc[Neo4j Drivers and APIs]

=== Cypher syntax basics

[.icon]
image:icon-syntax.svg[]

[.description]
A poster-style lookup reference for all of the Cypher queries, functions, and procedures.

[.link]
// xref:cypher-refcard:index.adoc[Cypher refcard]
link:{docs-home}/cypher-refcard[Cypher Refcard]

=== Neo4j Graph Data Science

[.category]
Neo4j Graph Data Science

[.icon]
image:icon-community-detection.svg[]

[.description]
For data scientists and analysts interested in scalable analytics powered by graph algorithms and machine learning models.

[.link]
link:{docs-home}/graph-data-science[Graph Data Science Library]

=== Extend Neo4j using Java

[.category]
Neo4j DBMS

[.icon]
image:icon-java.svg[]

[.description]
For Java developers looking to extend Neo4j’s functionality, or embed Neo4j in their own software.

[.link]
link:{docs-home}/java-reference[Java Developer Reference]

=== APOC

[.category]
Labs

[.icon]
image:icon-apoc.svg[]

[.description]
Discover Neo4j Labs; including the APOC library and a collection of the latest innovations in graph technology.

[.link]
link:https://neo4j.com/labs[Neo4j Labs]

[.display]
== Further resources

* Documentation for earlier releases is available from the version picker on each page.
For a complete list, please see our xref:resources:docs-archive.adoc[Documentation archive].
* Additionally, most of our documentation is available as a downloadable PDF.
For a full list of available PDFs, see the xref:resources:pdf-library.adoc[PDF library].

== License

© 2021 license: link:{docs-home}/license[Creative Commons 4.0]