= Run Cypher
:page-feedback: false
:page-includedriver: true

Runs a query against the link:https://demo.neo4jlabs.com:7473[`movies` database on the Neo4j Labs Demo Instance^].  The query runs in a transaction before being rolled back.

.Results on pageload:
[source,cypher,role=runnable instant]
MATCH (n) RETURN count(n) // `role=runnable instant`

.Mixed Results, Multiple Rows and role=editable
[source,cypher,role="runnable editable database:movies"]
MATCH (n:Person)-[r:ACTED_IN]->(m:Movie)
RETURN n,
    n.name,
    n.born,
    id(n) AS id,
    m.title,
    m.degree,
    type(r),
    id(r),
    r
LIMIT 10

.Syntax Error
[source,cypher,role=runnable editable]
MATCH (n) RETURN count

.Write Mode
[source,cypher,role=runnable database:movies mode:write]
MATCH (n) RETURN count(n)



See `src/js/07-runnable-code.js`.  At the moment URL, username and password are currently hardcoded:

[source,js]
window.neo4jDatabaseUri = 'neo4j+s://demo.neo4jlabs.com:7687'
window.neo4jDatabase = 'movies'
window.neo4jDriver = window.neo4j.driver(window.neo4jDatabaseUri, window.neo4j.auth.basic('movies', 'movies'))


== Config Options

* Runnable Statement:
** `[source,role=runnable]`
* Make it editable (Basic editing):
** `[source,role=editable]`
* Session/Query Mode (read, write)
** `[source,role=mode:read]`
** `[source,role=mode:write]`
* Modify DB:
** `[source,role=database:movies]`
** `[source,role=database:fincen]`
** `[source,role=database:etc]`
* Get instant results:
** `[source,role=instant]`