= Neo4j Labs
:description: Incubating the next generation of graph developer tooling. GraphQL and GRANDstack, Algorithms, APOC, Kafka, ETL Tool, neovis.js, and more.
// tag::layout[]
:page-layout: landing
:page-theme: labs
// end::layout[]
// :page-herotitle: Neo4j Labs
// :page-herosubtitle: Incubating the Next Generation of Graph Developer Tooling
:page-toclevels: -1
:page-disabletracking:

[.hero]
== Neo4j Labs

Incubating the Next Generation of +
Graph Developer Tooling

++++
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="none" style="enable-background:new 0 0 100 100;" xml:space="preserve" class="top"><polygon class="st0" points="100,100 0,100 100,0 "></polygon><line class="st1" x1="0" y1="100" x2="100" y2="0"></line></svg>
++++

[.buttons]
* <<What is Neo4j Labs?, About>>
* <<Current Projects>>
* <<Frequently Asked Questions, FAQs>>

// ++++
// <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="none" style="enable-background:new 0 0 100 100;" xml:space="preserve" class="bottom"><polygon class="st0" points="100,100 0,100 100,0 "></polygon><line class="st1" x1="0" y1="100" x2="100" y2="0"></line></svg>
// ++++

++++
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="none" style="enable-background:new 0 0 100 100;" xml:space="preserve" class="bottom to-leading"><polygon class="st0" points="100,100 0,100 100,0 "></polygon><line class="st1" x1="0" y1="100" x2="100" y2="0"></line></svg>
++++



[.secondary.leading]
== What is Neo4j Labs?

Neo4j Labs is a collection of the latest innovations in graph technology.
These projects are designed and developed by the Neo4j team as a way to test functionality and extensions of our product offerings.
A project typically either graduates to being maintained as a formal Neo4j project or is deprecated with source made available publicly.

These Labs are supported via the online community.
They are actively developed and maintained, but we don't provide any SLAs or guarantees around backwards compatibility and deprecation.


== Current Projects

=== Graph Algorithms Library

To enable large scale graph analytics and to support machine learning pipelines, we developed the link:https://neo4j.com/developer/graph-algorithms/[Neo4j Graph Algorithms^] library, which covers many widely used algorithms.
The library offers highly parallelized implementation that works well with large scale graphs.

[#goals.incremental]
=== xref:grandstack:index.adoc[GraphQL and GRANDstack]
GraphQL has become a comprehensive stack for API development and consolidation.
Our link:https://neo4j.com/labs/grandstack-graphql[GRANDstack^] and Neo4j-GraphQL-js offerings combine the most common tools and frameworks: GraphQL, React, Apollo and Neo4j Database.


=== xref:apoc:index.adoc[Awesome Procedures on Cypher (APOC)]

As the most comprehensive developer toolkit for Neo4j, the xref:apoc:index.adoc[APOC library] provides a wide range of procedures and functions that make your life as a Neo4j user easier.
APOC includes data integration, graph refactoring, data conversion, operational functionality and more.


=== xref:halin:index.adoc[Halin Monitoring App]

The link:https://neo4j.com/labs/halin[Halin Monitoring App] allows you to monitor your Neo4j deployment and identify bottlenecks or incorrect configurations, with insights into currently running queries and workloads.
The app also provides access to metrics and logs.


=== xref:streams:index.adoc[Kafka Integration]

Streaming event data is an integral part of most modern data architectures.
With xref:streams:index.adoc[Neo4j Kafka Integration] you can integrate Neo4j both as a sink or source into your setup.
The integration is available as a Kafka Connect plugin and Neo4j Server extension..


=== xref:etl:index.adoc[ETL Tool]

Having an easy way of loading data from relational databases into Neo4j is one of the first steps many users take.
The xref:etl:index.adoc[Neo4j-ETL Tool] makes this easy by inferring a graph model from the relational meta model that you can then adapt to fit your needs.
Given that transformation, this tool also handles the actual import for you.

=== xref:neosemantics:index.adoc[Neosemantics]

xref:neosemantics:index.adoc[Neosemantics] integrates RDF and Linked Data with Neo4j.
It allows to import a wide variety of RDF formats and to expose Neo4j property graphs as Linked Data.
Ontology and Inference are also partially supported.



=== Other Active Projects

* link:https://github.com/neo4j-contrib/neovis.js/[Neovis.js^], a graph visualization toolkit for the web
* link:https://github.com/neo4j-contrib/neo4j-spark-connector/[The Neo4j-Spark-Connector^], library to exchange graph data between Neo4j and Apache Spark

[.secondary]
== Frequently Asked Questions

=== Are these safe to use in production?
Current Neo4j Labs projects are being actively worked on by our engineers, and may be rough around the edges, with changing APIs, as they push the edge of the envelope. Therefore, we cannot provide official commercial support for these projects or guarantee longevity. However, some Neo4j customers and users still love the functionality of these projects and choose to continue using them in production environments.

=== How do I contribute?
We welcome contributions for those labs which are open source projects. You'll find links to GitHub repositories - feel free to submit PRs. We've also created a discussion category for Labs on link:https://community.neo4j.com[community.neo4j.com^]

=== Which Neo4j Labs projects have graduated?
The link:https://hub.docker.com/_/neo4j[Neo4j Docker containers] started off as a Labs project to explore how well Neo4j would run in a containerized environment. They quickly gained popularity and are heavily used by both Neo4j and customers, so we've graduated them to be officially part of the Neo4j release distribution.

We've also had features originally implemented as plugins and extensions moved into the core product. This includes link:https://neo4j.com/graphconnect-2018/session/neo4j-spatial-mapping[spatial functionality^] and APOC link:https://neo4j.com/docs/operations-manual/3.5/reference/procedures/[meta graph^] plus link:https://neo4j.com/docs/operations-manual/current/performance/index-configuration/fulltext/[full text indexing^].

=== Which Neo4j Labs projects have been deprecated?
The MongoDB Doc Manager and Cassandra Connector have both been deprecated. The source is still available on GitHub, but we found most developers could accomplish similiar goals by using APOC, Kafka and other technologies.

