= Promo Blocks
:author: Neo4j
:category: development
:tags: community, contributions, share
include::preview-src/promos-ad-include.adoc[]


For an example ad block in the sidebar, look to the right.
The attributes are set by the `include::` on line 5.

== Some non-graphacademy promo

[.promo]
====
This is something worthy to promote but it doesn't have an icon or anything.
====

== One Liner

[.promo.promo-graphacademy]
====
New to Neo4j? Take our free introductory
link:#[Neo4j Fundamentals course^].
====

[.promo.promo-graphacademy]
====
Learn everything about Graph Algorithms and Machine Learning Pipelines with our
link:#[Graph Data Science Fundamentals course^].
====

== Learning Path

[.promo.promo-graphacademy]
====
You can learn about this topic and so much more in our link:#[Data Reporting Learning Path^]:

* link:#[Foo Fundamentals^].
* link:#[Introduction to Bar^].
* link:#[Baz for Data Scientists^].
====

== Python Example

[.promo.promo-graphacademy]
====
Learn how to use the Neo4j Python Driver to build a Neo4j-backed movie recommendation website in the link:https://graphacademy.neo4j.com/courses/app-python/?ref=docs-promo[free Building Neo4j Applications with Python^] course on link:https://graphacademy.neo4j.com/?ref=docs-promo[Neo4j GraphAcademy^].
====

== Include Example

include::preview-src/promos-include.adoc[]
